# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "./build/tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./build/bin/desafio-verifymy ./cmd"

# Binary file yields from `cmd`.
bin = "./build/bin/desafio-verifymy"

# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]

# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "docs"]

# Exclude specific regular expressions.
exclude_regex = ["_test.go"]

# Exclude unchanged files.
exclude_unchanged = true

# Follow symlink for directories
follow_symlink = true

# This log file places in your tmp_dir.
log = "./build/logs/air.log"

# Stop running old binary when build errors occur.
stop_on_error = true

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false

# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
